version: '3.9'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  cv-evaluator:
    build: .
    container_name: cv-evaluator
    depends_on:
      - ollama
    environment:
      # Point to Ollama service inside Docker network
      OLLAMA_BASE_URL: http://ollama:11434
      # (add other env vars as needed)
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped

volumes:
  ollama_data:
